### ISSUE TITLE
Is there something like deadletter queue in RabbitMQ Stream?

### ISSUE THREAD

**Issue by garvenlee** [qweeze/rstream#158]
In one stream queue, consumption is sequential, but if my code fails to process certain message, it means this message is lost? For example, offset 5 failed, and offset 6-100 succeeded, how to handle this?

**Comment by Gsantomaggio** [comment]
> but if my code fails to process certain message, it means this message is lost? 

The stream consumer does not have the concept "ack/nack"  like AMQP.  The stream queue does not delete any message during the consuming part. 

So there is no concept of a dead letter in the stream since the message can be consumed more than one time by different consumers. 

You could implement it client-side like:
```python

 async def on_message(msg: AMQPMessage, message_context: MessageContext):
    try:
        data = json.loads(msg.....)
        print('Data Received:', data)
            
    except:
        print(f'error.......')
        dlq_producer.send(dlq_stream, msg)
        print('Message sent to DLQ stream'))
```

Or if you want you can use a Quorum AMQP queue as dead-letter queue

**Comment by garvenlee** [comment]
Ok, thanks. I will take a look
